SELECT OUTS.ANIMAL_ID, OUTS.ANIMAL_TYPE, OUTS.NAME
FROM ANIMAL_OUTS OUTS JOIN ANIMAL_INS INS ON OUTS.ANIMAL_ID=INS.ANIMAL_ID
WHERE OUTS.SEX_UPON_OUTCOME NOT LIKE 'Intact%' AND INS.SEX_UPON_INTAKE LIKE 'Intact%'
ORDER BY OUTS.ANIMAL_ID ASC;