SELECT YEAR(B.SALES_DATE) AS YEAR, MONTH(B.SALES_DATE) AS MONTH, COUNT(DISTINCT B.USER_ID) AS PUBCHASED_USER, ROUND(COUNT(DISTINCT B.USER_ID) / (SELECT COUNT(USER_ID) FROM USER_INFO WHERE YEAR(JOINED) = '2021'), 1) AS PUCHASED_RATIO
  FROM USER_INFO A
    LEFT JOIN ONLINE_SALE B
    ON A.USER_ID = B.USER_ID
  WHERE YEAR(A.JOINED) = '2021'
  GROUP BY DATE_FORMAT(B.SALES_DATE, '%Y-%m')
  HAVING YEAR IS NOT NULL
  ORDER BY YEAR, MONTH;