SELECT A.CAR_ID, A.CAR_TYPE, FLOOR(A.DAILY_FEE * (100-C.DISCOUNT_RATE) * 0.01 * 30) AS FEE
  FROM CAR_RENTAL_COMPANY_CAR A
    LEFT JOIN CAR_RENTAL_COMPANY_RENTAL_HISTORY B
    ON A.CAR_ID = B.CAR_ID
    LEFT JOIN CAR_RENTAL_COMPANY_DISCOUNT_PLAN C
    ON A.CAR_TYPE = C.CAR_TYPE
  WHERE A.CAR_TYPE IN ('세단', 'SUV') AND C.DURATION_TYPE LIKE '30%' AND A.DAILY_FEE * (100-C.DISCOUNT_RATE) * 0.01 * 30 BETWEEN 500000 AND 2000000 AND B.CAR_ID NOT IN (SELECT CAR_ID FROM CAR_RENTAL_COMPANY_RENTAL_HISTORY WHERE START_DATE <= '2022-11-30' AND END_DATE >= '2022-11-01')
  GROUP BY A.CAR_ID
  ORDER BY FEE DESC, A.CAR_TYPE, A.CAR_ID DESC;