SELECT A.FOOD_TYPE, A.REST_ID, A.REST_NAME, A.FAVORITES
  FROM REST_INFO A
    LEFT JOIN (SELECT FOOD_TYPE, MAX(FAVORITES) AS MAX_FAV FROM REST_INFO GROUP BY FOOD_TYPE) B
    ON A.FOOD_TYPE = B.FOOD_TYPE
  WHERE MAX_FAV = A.FAVORITES
  GROUP BY FOOD_TYPE
  ORDER BY FOOD_TYPE DESC;