SELECT B.HISTORY_ID,
  CASE
    WHEN (DATEDIFF(B.END_DATE, B.START_DATE) + 1) < 7 THEN (DATEDIFF(B.END_DATE, B.START_DATE) + 1) * A.DAILY_FEE
    ELSE FLOOR(MIN((DATEDIFF(B.END_DATE, B.START_DATE) + 1) * ((100 - C.DISCOUNT_RATE) / 100) * A.DAILY_FEE))
  END AS FEE
  FROM CAR_RENTAL_COMPANY_CAR A
    JOIN CAR_RENTAL_COMPANY_RENTAL_HISTORY B
    ON A.CAR_ID = B.CAR_ID
    JOIN CAR_RENTAL_COMPANY_DISCOUNT_PLAN C
    ON A.CAR_TYPE = C.CAR_TYPE
  WHERE A.CAR_TYPE IN ('트럭') AND ((DATEDIFF(B.END_DATE, B.START_DATE) + 1) < 7 OR (DATEDIFF(B.END_DATE, B.START_DATE) + 1) >= SUBSTRING(C.DURATION_TYPE, 1, INSTR(C.DURATION_TYPE, '일') - 1))
  GROUP BY B.HISTORY_ID
  ORDER BY FEE DESC, B.HISTORY_ID DESC;